collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7455197
  brandStrength: 0.8243728
  lightness: 0.5734767
  brandColors:
    - '#FFFFFF'
    - '#762B32'
    - '#756566'
    - '#A08C8E'
    - '#FCCFD2'
  rhythmicContrast: 0.6200717
typography_spectrum: 0.3064516
layout_spectrum: 0.5197133
name: Motionsolutions
