collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.5913978
color:
  saturation: 0.7625963
  brandStrength: 0.8243728
  lightness: 0.3191221
  brandColors:
    - '#0D0721'
    - '#FFFFFF'
    - '#491E65'
    - '#C86AFF'
    - '#FCB2FF'
  rhythmicContrast: 0.246466
layout_spectrum: 0.5197133
name: Motionsolutions
