layout_spectrum: 0.07251455
typography_spectrum: 0.1754402
color:
  saturation: 0.7625963
  lightness: 0.3191221
  brandStrength: 0.5195341
  rhythmicContrast: 0.246466
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Motionsolutions
